version: '2'

services:
  app:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - '8080:80'
    depends_on:
      - db
    links:
      - db
  db:
    hostname: db
    image: mysql
    restart: always
    volumes:
      - '.data/db:/var/lib/mysql'
    env_file:
      - .docker/env/mysql.env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    env_file:
      - '.docker/env/phpmyadmin.env'
    restart: always
    ports:
      - '8081:80'
    depends_on:
      - db
    links:
      - db
